### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ghost** [shankarapailoor/moonshine#3]
Hi,why could not I make it on aarch64?

[root@linux-Fuzzl moonshine]# make
ragel -Z -G2 -o scanner/lex.go scanner/lex.rl
goyacc -o scanner/strace.go -p Strace scanner/strace.y
mkdir -p bin deserialized
go build -o ./bin/moonshine main.go
go: finding github.com/shankarapailoor/moonshine latest
go: finding github.com/google/syzkaller latest
# github.com/shankarapailoor/moonshine/strace_types
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/strace_types/util.go:884:8: common.AddType undefined (type prog.ArgCommon has no field or method AddType)
# github.com/shankarapailoor/moonshine/distiller
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/distiller/distiller-metadata.go:111:12: call.Ret.Set undefined (type *prog.ResultArg has no field or method Set)
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/distiller/distiller-metadata.go:128:30: argK.(*prog.ResultArg).Set undefined (type *prog.ResultArg has no field or method Set)
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/distiller/distiller-metadata.go:131:33: argK.(*prog.ResultArg).Uses undefined (type *prog.ResultArg has no field or method Uses)
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/distiller/distiller-metadata.go:133:30: argK.(*prog.ResultArg).Set undefined (type *prog.ResultArg has no field or method Set)
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/distiller/distiller-metadata.go:136:29: argK.(*prog.ResultArg).Uses undefined (type *prog.ResultArg has no field or method Uses)
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/distiller/distiller-metadata.go:293:24: arg.(*prog.ResultArg).Set undefined (type *prog.ResultArg has no field or method Set)
../../syzkaller/pkg/mod/github.com/shankarapailoor/moonshine@v0.0.0-20190509180242-95e5f6dfd276/distiller/random-distiller.go:111:4: p.StripDependencies undefined (type *prog.Prog has no field or method StripDependencies)
make: *** [Makefile:5: default] Error 2

**Comment by ghost** [comment]
Using original code ,it appears errors with ragel：
![image](https://user-images.githubusercontent.com/52522159/77269524-14786800-6ce4-11ea-9839-e36b4dd8d927.png)
The lex.go file  looks like have some  syntax errors:
![image](https://user-images.githubusercontent.com/52522159/77269632-67521f80-6ce4-11ea-87ca-cbc86d830b7a.png)

I tried to copy the file 'straceLex.rl ' from  syzkaller/tool/syz-trace2syz/parser  to moonshine/scanner,then modified the Makefile  like this:
![image](https://user-images.githubusercontent.com/52522159/77270011-974df280-6ce5-11ea-9446-7c0646c4cd5e.png)

then I still got make errors,know a little about Go,really dont know how to solve it :(

![image](https://user-images.githubusercontent.com/52522159/77270334-9ec1cb80-6ce6-11ea-9f03-4ed00efdb712.png)

**Comment by shankarapailoor** [comment]
Hi!

Can you tell me the version of golang are you using?

**Comment by ghost** [comment]
> Hi!
> 
> Can you tell me the version of golang are you using?

Hi,my golang version :
![image](https://user-images.githubusercontent.com/52522159/77288078-fe819c00-6d11-11ea-8718-f33cfd5d2a89.png)

Now I noticed another repo you opened in github:
https://github.com/shankarapailoor/trace2syz
and this repo I can build out a tool named trace2syz. Now I'm trying to use it to produce a 'corpus.db'.But also I got confused should I use this version of stace？
https://github.com/shankarapailoor/strace
cause it seems got some build errors on a aarch64 machine.

**Comment by shankarapailoor** [comment]
Unfortunately our modified strace is limited to x86 architectures so it would not work on aarch64.

**Comment by ghost** [comment]
#
